### ISSUE TITLE
Subroutine description when using continuation sign is not found

### ISSUE THREAD

**Issue by rochusschmid** [VACUMM/sphinx-fortran#5]
Hello sphinx-fortran team,
this is a great and very helpful project!
It seems to me that a subroutine description is not properly read when using autosubroutine in case of a continuation line. The documentation says the description comment is used "if they start immediately after the declaration line." If I break the declaration line and use "&" then the description is not used any more (probably because it is not directly following "subroutine").
for readability I would prefer to break the parameters over multiple lines.
Any chances to fix that easily?
best,
  rochus

**Comment by jowilk** [comment]
Hi rochusschmid and thank you for reporting this, it should now be fixed.
Regards
